title: "Evangelos Lamprou"
tagline: ""
description: "Evangelos (Vagozino) Lamprou - Web"
github_username: "vagos"
baseurl: ""
url: "https://vagos.github.io/"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-scholar

sass:
  style: compressed

highlighter: rouge

collections:

  blog:
    output: true

  drafts:
    output: false

header_pages:
  - pages/index.md
  - pages/things.md
  - pages/about.md
  - pages/posts.md

# set the size of the text to 'large' or 'small', default is small
font-size: small

scholar:
  style: apa
  bibliography_template: bib

feed:
  collections:
    - blog

exclude:
  - makefile
